//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAccountGroup
    {
        public int AccountGroupId { get; set; }
        public string AccountGroup { get; set; }
        public Nullable<int> AccountType { get; set; }
        public string AccountGroupCode { get; set; }
        public Nullable<System.DateTime> CreatedTS { get; set; }
        public Nullable<int> CreatedUserId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTS { get; set; }
        public Nullable<int> LastUpdatedUserId { get; set; }
        public Nullable<int> SeqNbr { get; set; }
        public string Status { get; set; }
        public Nullable<bool> Is_Subgroup { get; set; }
        public Nullable<int> ParentgroupId { get; set; }
        public Nullable<bool> Bank_f { get; set; }
    }
}
