//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAccountHead
    {
        public int AccountHeadId { get; set; }
        public Nullable<int> AccountGroupId { get; set; }
        public string AccountHead { get; set; }
        public string AccountHeadCode { get; set; }
        public Nullable<int> CrtdUserId { get; set; }
        public Nullable<System.DateTime> CrtdTS { get; set; }
        public Nullable<int> SeqNbr { get; set; }
        public Nullable<int> LastUpdatedUserId { get; set; }
        public Nullable<System.DateTime> Lastupdated_TS { get; set; }
        public string Status { get; set; }
        public Nullable<bool> Bank_f { get; set; }
    }
}
