//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAdhocPayment
    {
        public int AdhocPaymentId { get; set; }
        public Nullable<int> PayeeType { get; set; }
        public string PayeeID { get; set; }
        public string PayeeName { get; set; }
        public string AdhocPaymentNumber { get; set; }
        public Nullable<int> AdhocPaymentType { get; set; }
        public Nullable<int> AdhocPaymentMode { get; set; }
        public Nullable<int> SourceReferenceNumber { get; set; }
        public Nullable<System.DateTime> SourceEmailDate { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<decimal> TotalTaxAmount { get; set; }
        public Nullable<decimal> NetPayableAmount { get; set; }
        public Nullable<decimal> EligibleTaxAmount { get; set; }
        public Nullable<int> Source { get; set; }
        public string Remarks { get; set; }
        public string TransactionTypeCode { get; set; }
        public string BankName { get; set; }
        public string BankBranch { get; set; }
        public string AccountNumber { get; set; }
        public string IFSC { get; set; }
        public Nullable<int> CRTD_By { get; set; }
        public Nullable<System.DateTime> CRTD_TS { get; set; }
        public Nullable<int> UPTD_By { get; set; }
        public Nullable<System.DateTime> UPTD_TS { get; set; }
        public string Status { get; set; }
        public Nullable<int> CheckListVerifiedBy { get; set; }
        public Nullable<int> CommitmentId { get; set; }
        public Nullable<bool> Pmt_f { get; set; }
    }
}
