//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAdhocPayInvoiceDetails
    {
        public int AdhocPayinvId { get; set; }
        public Nullable<int> AdhocPaymentId { get; set; }
        public string InvoiceNumber { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<decimal> TaxablePercentage { get; set; }
        public Nullable<decimal> TaxValue { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string GSTIN { get; set; }
        public Nullable<bool> IsTaxEligible { get; set; }
        public Nullable<int> CRTD_By { get; set; }
        public Nullable<System.DateTime> CRTD_TS { get; set; }
        public Nullable<int> UPTD_By { get; set; }
        public Nullable<System.DateTime> UPTD_TS { get; set; }
        public string Status { get; set; }
    }
}
