//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBankAccountMapping
    {
        public int Id { get; set; }
        public Nullable<int> BankAccountId { get; set; }
        public string BankName { get; set; }
        public string BankAccountNumber { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string CategoryName { get; set; }
        public Nullable<int> ClassificationCode { get; set; }
        public Nullable<int> ProjectType { get; set; }
        public Nullable<int> ProjectScheme { get; set; }
    }
}
