//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBOATransaction
    {
        public int BOATransactionId { get; set; }
        public Nullable<int> BOAId { get; set; }
        public Nullable<int> AccountHeadId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string TransactionType { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> Creditor_f { get; set; }
        public Nullable<bool> Debtor_f { get; set; }
        public Nullable<int> SubLedgerType { get; set; }
    }
}
