//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBOA
    {
        public int BOAId { get; set; }
        public Nullable<System.DateTime> PostedDate { get; set; }
        public Nullable<int> VoucherType { get; set; }
        public string TempVoucherNumber { get; set; }
        public string VoucherNumber { get; set; }
        public string TransactionTypeCode { get; set; }
        public string Narration { get; set; }
        public Nullable<int> PaymentMode { get; set; }
        public string Status { get; set; }
        public Nullable<int> RefBOAId { get; set; }
        public Nullable<decimal> BOAValue { get; set; }
        public string RefTransactionCode { get; set; }
        public string RefNumber { get; set; }
    }
}
