//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBankAccountMaster
    {
        public int BankAccountId { get; set; }
        public Nullable<int> BankId { get; set; }
        public string AccountNumber { get; set; }
        public string BankAccountType { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> CrtdUserId { get; set; }
        public Nullable<System.DateTime> CrtdTS { get; set; }
        public Nullable<int> UpdtUserId { get; set; }
        public Nullable<System.DateTime> UpdtTS { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
