//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblClearancePaymentTDSDetail
    {
        public int ClearancePaymentTDSDetailId { get; set; }
        public Nullable<int> ClearanceAgentTDSDetailId { get; set; }
        public Nullable<int> ClearancePaymentId { get; set; }
        public Nullable<int> CRTD_By { get; set; }
        public Nullable<System.DateTime> CRTD_TS { get; set; }
        public string Status { get; set; }
    }
}
