//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCodeControl
    {
        public int CodeID { get; set; }
        public string CodeName { get; set; }
        public int CodeValAbbr { get; set; }
        public string CodeValDetail { get; set; }
        public string CodeDescription { get; set; }
        public Nullable<int> UPDT_UserID { get; set; }
        public Nullable<System.DateTime> CRTE_TS { get; set; }
        public Nullable<System.DateTime> UPDT_TS { get; set; }
    }
}
