//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblClearanceAgentMaster
    {
        public int ClearanceAgentId { get; set; }
        public Nullable<int> Nationality { get; set; }
        public string ClearanceAgentCode { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string ContactPerson { get; set; }
        public string PhoneNumber { get; set; }
        public string MobileNumber { get; set; }
        public string RegisteredName { get; set; }
        public string PAN { get; set; }
        public string TAN { get; set; }
        public Nullable<bool> GSTExempted { get; set; }
        public string Reason { get; set; }
        public string GSTIN { get; set; }
        public string AccountHolderName { get; set; }
        public string BankName { get; set; }
        public string Branch { get; set; }
        public string IFSC { get; set; }
        public string AccountNumber { get; set; }
        public string BankAddress { get; set; }
        public string ABANumber { get; set; }
        public string SortCode { get; set; }
        public string IBAN { get; set; }
        public string SWIFTorBICCode { get; set; }
        public string TypeofService { get; set; }
        public Nullable<bool> ReverseTax { get; set; }
        public Nullable<bool> TDSExcempted { get; set; }
        public string CertificateNumber { get; set; }
        public Nullable<int> ValidityPeriod { get; set; }
        public Nullable<System.DateTime> CRTD_TS { get; set; }
        public Nullable<System.DateTime> UPDT_TS { get; set; }
        public Nullable<int> CRTD_UserID { get; set; }
        public Nullable<int> UPDT_UserID { get; set; }
        public string Status { get; set; }
        public Nullable<int> SeqNbr { get; set; }
        public Nullable<int> Country { get; set; }
        public Nullable<int> StateCode { get; set; }
        public Nullable<int> StateId { get; set; }
    }
}
