//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCurrency
    {
        public int CurrencyID { get; set; }
        public string CurrencyUnit { get; set; }
        public string Symbol { get; set; }
        public string ISOCode { get; set; }
        public string HTMLDecimalCode { get; set; }
        public string HTMLHexCode { get; set; }
        public string DecimalUnicode { get; set; }
        public string HexUnicode { get; set; }
        public Nullable<int> Country { get; set; }
    }
}
