//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCommitmentLog
    {
        public int CommitmentLogId { get; set; }
        public Nullable<int> CommitmentDetailID { get; set; }
        public Nullable<decimal> OldAmount { get; set; }
        public Nullable<decimal> NewAmount { get; set; }
        public Nullable<int> RefId { get; set; }
        public string TransactionTypeCode { get; set; }
        public Nullable<System.DateTime> CRTD_TS { get; set; }
        public Nullable<int> CRTD_By { get; set; }
        public Nullable<bool> Reversed_f { get; set; }
        public Nullable<bool> Reject_f { get; set; }
    }
}
