//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblClearancePaymentEntry
    {
        public int ClearancePaymentId { get; set; }
        public string TransactionTypeCode { get; set; }
        public Nullable<int> SourceReferenceNumber { get; set; }
        public Nullable<System.DateTime> SourceEmailDate { get; set; }
        public Nullable<int> Source { get; set; }
        public string BillNumber { get; set; }
        public Nullable<int> ClearancePaymentAgentId { get; set; }
        public Nullable<System.DateTime> ReferencePODate { get; set; }
        public string ReferencePONumber { get; set; }
        public Nullable<decimal> AdvancePercentage { get; set; }
        public Nullable<int> BillType { get; set; }
        public Nullable<decimal> BillAmount { get; set; }
        public Nullable<decimal> BillTaxAmount { get; set; }
        public Nullable<int> CommitmentId { get; set; }
        public Nullable<decimal> CommitmentAmount { get; set; }
        public Nullable<decimal> ExpenseAmount { get; set; }
        public Nullable<decimal> DeductionAmount { get; set; }
        public Nullable<System.DateTime> CRTD_TS { get; set; }
        public Nullable<System.DateTime> UPTD_TS { get; set; }
        public Nullable<int> CRTD_By { get; set; }
        public Nullable<int> UPTD_By { get; set; }
        public string Status { get; set; }
        public Nullable<int> CheckListVerifiedBy { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<int> PaymentType { get; set; }
        public Nullable<bool> PartAdvance_f { get; set; }
        public Nullable<bool> InclusiveOfTax_f { get; set; }
        public Nullable<bool> Pmt_f { get; set; }
    }
}
