//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDistributionDetails
    {
        public int DistributionDetailsId { get; set; }
        public Nullable<int> DistributionId { get; set; }
        public string Category { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Name { get; set; }
        public string PayBillNumber { get; set; }
        public string ProjectNumber { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> TDSAmount { get; set; }
        public Nullable<decimal> NetAmount { get; set; }
        public Nullable<int> PaymentMode { get; set; }
        public string BankName { get; set; }
        public string BankBranch { get; set; }
        public string AccountNumber { get; set; }
        public Nullable<bool> PaymentCompleted_f { get; set; }
        public string IFSC { get; set; }
        public Nullable<int> CRTD_By { get; set; }
        public Nullable<System.DateTime> CRTD_TS { get; set; }
        public Nullable<int> UPTD_By { get; set; }
        public Nullable<System.DateTime> UPTD_TS { get; set; }
        public string Status { get; set; }
        public string FacultyDepartment { get; set; }
        public string FacultyDesignation { get; set; }
    }
}
