//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDistributeInstituteOHBreakup
    {
        public int InstituteOverheadbreakupId { get; set; }
        public Nullable<int> DistributionId { get; set; }
        public Nullable<int> InstituteOverheadTypeId { get; set; }
        public string InstituteOverheadType { get; set; }
        public Nullable<decimal> InstituteOverheadAmount { get; set; }
        public Nullable<decimal> InstituteOverheadPercentage { get; set; }
        public Nullable<System.DateTime> CrtdTS { get; set; }
        public Nullable<int> CrtdUserId { get; set; }
        public Nullable<System.DateTime> UpdtTS { get; set; }
        public Nullable<int> UpdtUserId { get; set; }
        public string Status { get; set; }
        public Nullable<bool> IsRMF_f { get; set; }
        public Nullable<bool> ISCMF_f { get; set; }
    }
}
