//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDistributionPCFDetails
    {
        public int DistributionPCFDetailsId { get; set; }
        public Nullable<int> DistributionId { get; set; }
        public string PCFPIName { get; set; }
        public string PCFPIUserId { get; set; }
        public string PCFPIDepartment { get; set; }
        public string PCFPIDesignation { get; set; }
        public string PIPCFId { get; set; }
        public Nullable<decimal> PCFAmount { get; set; }
        public Nullable<int> CRTD_By { get; set; }
        public Nullable<System.DateTime> CRTD_TS { get; set; }
        public string Status { get; set; }
    }
}
