//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDynamicReports
    {
        public int ReportID { get; set; }
        public string ReportName { get; set; }
        public string Description { get; set; }
        public string TableName { get; set; }
        public string Fields { get; set; }
        public string GroupByFields { get; set; }
        public string OrderByFields { get; set; }
        public Nullable<int> RoleID { get; set; }
        public Nullable<int> ModuleID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CRTD_TS { get; set; }
        public Nullable<System.DateTime> UPDT_TS { get; set; }
        public Nullable<int> CRTD_UserID { get; set; }
        public Nullable<int> UPDT_UserID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
