//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDistribution
    {
        public int DistributionId { get; set; }
        public Nullable<int> DistributionType { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> PIId { get; set; }
        public string PIName { get; set; }
        public string DistributionNumber { get; set; }
        public Nullable<int> SourceReferenceNumber { get; set; }
        public Nullable<System.DateTime> SourceEmailDate { get; set; }
        public string LabCode { get; set; }
        public Nullable<decimal> ToLabCodeAmount { get; set; }
        public Nullable<decimal> EUCOAmount { get; set; }
        public Nullable<decimal> StoresConsumedAmount { get; set; }
        public Nullable<decimal> DistributionAmount { get; set; }
        public Nullable<decimal> CentralFacilitiesAmount { get; set; }
        public Nullable<decimal> OthersAmount { get; set; }
        public Nullable<decimal> AmountToIITAccount { get; set; }
        public Nullable<decimal> AmountAvailableforDistribution { get; set; }
        public Nullable<decimal> AvailableBalance { get; set; }
        public Nullable<decimal> InstituteOverhead { get; set; }
        public Nullable<decimal> InstituteOverheadPercentage { get; set; }
        public Nullable<decimal> TotalIndividualShare { get; set; }
        public Nullable<decimal> TotalPCF { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<decimal> TotalTDS { get; set; }
        public Nullable<decimal> TotalIndividualPayableAmount { get; set; }
        public Nullable<int> Source { get; set; }
        public string Remarks { get; set; }
        public string TransactionTypeCode { get; set; }
        public Nullable<int> CRTD_By { get; set; }
        public Nullable<System.DateTime> CRTD_TS { get; set; }
        public Nullable<int> UPTD_By { get; set; }
        public Nullable<System.DateTime> UPTD_TS { get; set; }
        public string Status { get; set; }
        public Nullable<int> CheckListVerifiedBy { get; set; }
        public Nullable<int> CommitmentId { get; set; }
        public Nullable<System.DateTime> MonthandYear { get; set; }
        public Nullable<bool> PaymentProcess_f { get; set; }
        public Nullable<bool> Pmt_f { get; set; }
    }
}
