//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDeductionHead
    {
        public int DeductionHeadId { get; set; }
        public Nullable<int> AccountHeadId { get; set; }
        public string TransactionTypeCode { get; set; }
        public Nullable<bool> EligibleForOffset_f { get; set; }
        public Nullable<int> DeductionCategoryId { get; set; }
        public Nullable<bool> Interstate_f { get; set; }
        public string DeductionType { get; set; }
        public Nullable<bool> EligibilityCheck_f { get; set; }
    }
}
