//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDepartment
    {
        public int DepartmentId { get; set; }
        public string DepartmentName { get; set; }
        public string HOD { get; set; }
        public Nullable<int> CreatedUserId { get; set; }
        public Nullable<int> LastUpdateUserId { get; set; }
        public Nullable<System.DateTime> CreatedTS { get; set; }
        public Nullable<System.DateTime> UpdatedTS { get; set; }
        public string Status { get; set; }
        public Nullable<int> UpdateUserId { get; set; }
        public Nullable<System.DateTime> LastUpdated_TS { get; set; }
    }
}
