//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEvent
    {
        public int EventId { get; set; }
        public string EventTitle { get; set; }
        public Nullable<System.DateTime> EventStart { get; set; }
        public Nullable<System.DateTime> EventEnd { get; set; }
        public string Url { get; set; }
        public Nullable<bool> allDay { get; set; }
        public string Start { get; set; }
        public string End { get; set; }
        public Nullable<System.DateTime> CreatedTS { get; set; }
        public Nullable<System.DateTime> LastUpdatedTS { get; set; }
        public Nullable<int> CreatedUserId { get; set; }
        public Nullable<int> LastUpdatedUserId { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
