//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmpSOPIncome
    {
        public int ID { get; set; }
        public Nullable<decimal> EligibleAmount { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> EmpId { get; set; }
        public string EmpNo { get; set; }
        public Nullable<System.DateTime> SubmittedOn { get; set; }
        public string LenderName { get; set; }
        public string LenderPAN { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    }
}
