//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFunction
    {
        public int FunctionId { get; set; }
        public string FunctionName { get; set; }
        public string ActionName { get; set; }
        public string ControllerName { get; set; }
        public Nullable<int> ModuleID { get; set; }
        public Nullable<int> MenuGroupID { get; set; }
        public Nullable<int> MenuSeq { get; set; }
    }
}
