//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGstDocument
    {
        public int GstVendorDocumentId { get; set; }
        public Nullable<int> VendorId { get; set; }
        public string GstVendorDocument { get; set; }
        public string GstAttachmentPath { get; set; }
        public string GstAttachmentName { get; set; }
        public Nullable<int> GstDocumentType { get; set; }
        public Nullable<bool> IsCurrentVersion { get; set; }
        public Nullable<int> GstDocumentUploadUserId { get; set; }
        public Nullable<System.DateTime> GstDocumentUpload_Ts { get; set; }
    }
}
