//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHonororiumPCFDetail
    {
        public int tblHonororiumPCFDetail1 { get; set; }
        public Nullable<int> HonororiumId { get; set; }
        public string PayeeName { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> PayableToPCF { get; set; }
        public Nullable<decimal> PayableToOH { get; set; }
        public Nullable<int> PayeeID { get; set; }
        public string status { get; set; }
        public string OHPercentage { get; set; }
    }
}
