//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHeadOBDeletedLog
    {
        public int AccountHeadOBDeletedId { get; set; }
        public Nullable<int> AccountHeadId { get; set; }
        public Nullable<decimal> CurrentOBBalance { get; set; }
        public Nullable<int> CurrentFinYearId { get; set; }
        public Nullable<int> DeleteUserId { get; set; }
        public Nullable<System.DateTime> Delete_Ts { get; set; }
    }
}
