//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInstallment
    {
        public int InstallmentID { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> InstallmentNo { get; set; }
        public Nullable<decimal> InstallmentValue { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> NoOfInstallment { get; set; }
        public Nullable<decimal> InstallmentValueForYear { get; set; }
    }
}
