//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInstituteMaster
    {
        public int InstituteId { get; set; }
        public string Institutename { get; set; }
        public string Institutecode { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Location { get; set; }
        public string State { get; set; }
        public Nullable<int> Country { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Designation { get; set; }
        public string Email { get; set; }
        public Nullable<int> CRTE_UserID { get; set; }
        public Nullable<System.DateTime> CRTE_TS { get; set; }
        public Nullable<int> UPDT_UserID { get; set; }
        public Nullable<System.DateTime> UPDT_TS { get; set; }
        public string Zipcode { get; set; }
        public string ContactMobile { get; set; }
        public Nullable<System.DateTime> Deleteddate { get; set; }
        public Nullable<int> Deleteduserid { get; set; }
        public string logoURL { get; set; }
        public string Deletereason { get; set; }
        public string Status { get; set; }
        public Nullable<int> LastUpdatedUserId { get; set; }
    }
}
