//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblIITMBankMaster
    {
        public int BankId { get; set; }
        public string BankName { get; set; }
        public string BranchName { get; set; }
        public string BankBranchCode { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string District { get; set; }
        public string State { get; set; }
        public Nullable<int> PinCode { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string ContactPerson { get; set; }
        public string IFSC { get; set; }
        public string MICR { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> CrtdUserId { get; set; }
        public Nullable<System.DateTime> CrtdTS { get; set; }
        public Nullable<int> UpdtUserId { get; set; }
        public Nullable<System.DateTime> UpdtTS { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
