//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblIMPUserDetails
    {
        public int IMPUserDetailsId { get; set; }
        public string ImprestCardNumber { get; set; }
        public Nullable<int> ImprestBank { get; set; }
        public string ImprestACNumber { get; set; }
        public Nullable<decimal> ImprestTotalValue { get; set; }
        public Nullable<int> NoofImprests { get; set; }
        public Nullable<int> PIUserId { get; set; }
        public string PIFirstName { get; set; }
        public string PIFatherFirstName { get; set; }
        public string PIMotherMaidenName { get; set; }
        public Nullable<System.DateTime> Dateofbirth { get; set; }
        public Nullable<int> Gender { get; set; }
        public string PIMobileNumber { get; set; }
        public string PIEmailId { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string District { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Pincode { get; set; }
        public string Status { get; set; }
        public string PIPAN { get; set; }
        public Nullable<System.DateTime> CrtdTS { get; set; }
        public Nullable<int> CrtdUserId { get; set; }
        public Nullable<System.DateTime> UpdtTS { get; set; }
        public Nullable<int> UpdtUserId { get; set; }
        public string ImprestNumber { get; set; }
        public string TransactionTypeCode { get; set; }
    }
}
