//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblITDeclaration
    {
        public int DeclarationID { get; set; }
        public Nullable<int> SNO { get; set; }
        public string SectionName { get; set; }
        public string SectionCode { get; set; }
        public string Particulars { get; set; }
        public Nullable<decimal> MaxLimit { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    }
}
