//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblJointDevelopmentCompany
    {
        public int JointDevelopCompanyId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public string JointDevelopCompanyName { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> CrtdTS { get; set; }
        public Nullable<int> CrtdUserID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> UpdtUserID { get; set; }
        public Nullable<System.DateTime> UpdtdTS { get; set; }
    }
}
