//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNotification
    {
        public int NotificationId { get; set; }
        public string NotificationType { get; set; }
        public Nullable<int> FromUserId { get; set; }
        public Nullable<int> ToUserId { get; set; }
        public string Subject { get; set; }
        public string Description { get; set; }
        public string FunctionURL { get; set; }
        public int ReferenceId { get; set; }
        public Nullable<System.DateTime> Crt_Ts { get; set; }
        public Nullable<int> Crt_By { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
