//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNegativeBalance
    {
        public int NegativeBalanceId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> PIId { get; set; }
        public string NegativeBalanceNumber { get; set; }
        public Nullable<System.DateTime> RequestedDate { get; set; }
        public Nullable<decimal> ClaimAmount { get; set; }
        public Nullable<decimal> ReceiptAdjustmentAmount { get; set; }
        public Nullable<decimal> NegativeBalanceAmount { get; set; }
        public Nullable<int> SourceReferenceNumber { get; set; }
        public Nullable<System.DateTime> SourceEmailDate { get; set; }
        public Nullable<int> Source { get; set; }
        public string Remarks { get; set; }
        public string TransactionTypeCode { get; set; }
        public string NegativeBalanceDocPath { get; set; }
        public string NegativeBalanceCloseDocPath { get; set; }
        public Nullable<int> CRTD_By { get; set; }
        public Nullable<System.DateTime> CRTD_TS { get; set; }
        public Nullable<int> UPTD_By { get; set; }
        public Nullable<System.DateTime> UPTD_TS { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> ClosedDate { get; set; }
        public string ReasonForClose { get; set; }
        public Nullable<decimal> BalanceWhenClosing { get; set; }
        public string DocumentActualName { get; set; }
        public string RemarksForClose { get; set; }
    }
}
