//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOtherInstituteCoPI
    {
        public int CoPIId { get; set; }
        public Nullable<int> ProposalId { get; set; }
        public string Name { get; set; }
        public string Institution { get; set; }
        public string Department { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> Crtd_TS { get; set; }
        public Nullable<int> CrtdUserId { get; set; }
        public Nullable<System.DateTime> Updt_TS { get; set; }
        public Nullable<int> UpdtUserId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> DeletedUserid { get; set; }
    }
}
