//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOverheadsPercentage
    {
        public int OverheadsTypeId { get; set; }
        public Nullable<int> ProjectType { get; set; }
        public string Overheads { get; set; }
        public Nullable<decimal> Percentage { get; set; }
        public Nullable<int> ProjectCategory { get; set; }
    }
}
