//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOverheadsPostingDetails
    {
        public int OverheadsDetailsId { get; set; }
        public Nullable<int> OverheadsPostingId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> PIId { get; set; }
        public Nullable<int> ReceiptId { get; set; }
        public Nullable<int> ReceiptOverheadbreakupId { get; set; }
        public Nullable<int> ReceiptOverheadTypeId { get; set; }
        public Nullable<decimal> TotalOverheadsAmount { get; set; }
        public Nullable<decimal> CorpusPercent { get; set; }
        public Nullable<decimal> CorpousAmount { get; set; }
        public Nullable<decimal> RMFPercent { get; set; }
        public Nullable<decimal> RMFAmount { get; set; }
        public Nullable<decimal> ICSROHPercent { get; set; }
        public Nullable<decimal> ICSROHAmount { get; set; }
        public Nullable<decimal> DDFPercent { get; set; }
        public Nullable<decimal> DDFAmount { get; set; }
        public Nullable<decimal> StaffWelfarePercent { get; set; }
        public Nullable<decimal> StaffWelfareAmount { get; set; }
        public Nullable<decimal> PCFPercent { get; set; }
        public Nullable<decimal> PCFAmount { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<System.DateTime> CRTD_TS { get; set; }
        public Nullable<int> CRTD_By { get; set; }
        public Nullable<System.DateTime> UPTD_TS { get; set; }
        public Nullable<int> UPTD_By { get; set; }
        public string Status { get; set; }
    }
}
