//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPartTimeStudentDetails
    {
        public int PartTimeStudentId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> PaymentId { get; set; }
        public string StudentName { get; set; }
        public Nullable<int> Session { get; set; }
        public string Email { get; set; }
        public string RollNo { get; set; }
        public string Course { get; set; }
        public Nullable<int> YearofStudy { get; set; }
        public Nullable<System.DateTime> InternStartDate { get; set; }
        public Nullable<System.DateTime> InternCloseDate { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<decimal> StipendAmountperHour { get; set; }
        public Nullable<decimal> TotalStipend { get; set; }
        public string Remarks { get; set; }
        public string BankName { get; set; }
        public string AccountNumber { get; set; }
        public string BranchName { get; set; }
        public string IFSCCode { get; set; }
        public Nullable<int> CRTD_By { get; set; }
        public Nullable<System.DateTime> CRTD_TS { get; set; }
        public Nullable<int> UPTD_By { get; set; }
        public Nullable<System.DateTime> UPTD_TS { get; set; }
        public string Status { get; set; }
    }
}
