//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProjectEnhancementAllocation
    {
        public int ProjectEnhancementAllocationId { get; set; }
        public Nullable<int> ProjectEnhancementId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> AllocationHead { get; set; }
        public Nullable<decimal> OldValue { get; set; }
        public Nullable<decimal> EnhancedValue { get; set; }
        public Nullable<decimal> TotalValue { get; set; }
        public Nullable<int> CrtdUserId { get; set; }
        public Nullable<System.DateTime> CrtdTS { get; set; }
        public Nullable<bool> IsCurrentVersion { get; set; }
        public string Status { get; set; }
    }
}
