//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProcessGuidelineWorkFlow
    {
        public int ProcessGuidelineWorkFlowId { get; set; }
        public Nullable<int> ProcessGuidelineId { get; set; }
        public Nullable<int> ProcessGuidelineDetailId { get; set; }
        public Nullable<int> ApproverId { get; set; }
        public Nullable<int> ApproverLevel { get; set; }
        public Nullable<bool> Approve_f { get; set; }
        public Nullable<bool> Reject_f { get; set; }
        public Nullable<bool> Clarify_f { get; set; }
        public Nullable<bool> Mark_f { get; set; }
        public Nullable<System.DateTime> CreatedTS { get; set; }
        public Nullable<int> CreatedUserId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTS { get; set; }
        public Nullable<int> LastUpdatedUserId { get; set; }
        public Nullable<int> StatusId { get; set; }
    }
}
