//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProject
    {
        public int ProjectId { get; set; }
        public string ProposalNumber { get; set; }
        public Nullable<int> FinancialYear { get; set; }
        public Nullable<int> ProjectType { get; set; }
        public Nullable<int> ProjectSubType { get; set; }
        public Nullable<int> SchemeName { get; set; }
        public string SchemeAgencyName { get; set; }
        public string SchemePersonApplied { get; set; }
        public string SchemePersonDesignation { get; set; }
        public string PIDepartment { get; set; }
        public Nullable<int> PIName { get; set; }
        public Nullable<int> PIDesignation { get; set; }
        public Nullable<int> FundingType { get; set; }
        public Nullable<int> IndianFundedBy { get; set; }
        public Nullable<int> FundingGovtBody { get; set; }
        public Nullable<int> FundingNonGovtBody { get; set; }
        public Nullable<int> ForeignFundedBy { get; set; }
        public Nullable<int> ProjectCategory { get; set; }
        public string ProjectTitle { get; set; }
        public Nullable<int> CategoryOfProject { get; set; }
        public Nullable<decimal> SanctionValue { get; set; }
        public Nullable<int> ConsultancyFundingCategory { get; set; }
        public Nullable<int> ConsultancyTaxServiceType { get; set; }
        public Nullable<int> ProjectAgencyCountry { get; set; }
        public string IndianProjectAgencyState { get; set; }
        public string IndianProjectAgencyLocation { get; set; }
        public string TaxExemptionReason { get; set; }
        public string TaxExemptionDocPath { get; set; }
        public string GSTIN { get; set; }
        public string PAN { get; set; }
        public string TAN { get; set; }
        public Nullable<int> SponsoringAgency { get; set; }
        public Nullable<int> SponsoringAgencyCode { get; set; }
        public string SponsoringAgencyAddress { get; set; }
        public string SponsoringAgencySOAddress { get; set; }
        public string SponsoringAgencyContactPerson { get; set; }
        public string SponsoringAgencyContactPersonDesignation { get; set; }
        public string SponsoringAgencyContactPersonEmail { get; set; }
        public string SponsoringAgencyContactPersonMobile { get; set; }
        public Nullable<System.DateTime> TentativeStartDate { get; set; }
        public Nullable<System.DateTime> ActualStartDate { get; set; }
        public Nullable<System.DateTime> TentativeCloseDate { get; set; }
        public Nullable<System.DateTime> ActuaClosingDate { get; set; }
        public string AttachmentName { get; set; }
        public string AttachmentPath { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> UpdatedUserId { get; set; }
        public Nullable<System.DateTime> UpdatedTS { get; set; }
        public string ProjectNumber { get; set; }
        public Nullable<int> ProposalId { get; set; }
        public Nullable<System.DateTime> ProposalApprovedDate { get; set; }
        public Nullable<int> FundingGovtMinistry { get; set; }
        public string SponProjectCategory { get; set; }
        public string ForeignProjectAgencyState { get; set; }
        public string ForeignProjectAgencyLocation { get; set; }
        public Nullable<int> TotalProjectStaffCount { get; set; }
        public Nullable<int> SumofStaffCount { get; set; }
        public Nullable<decimal> SumSalaryofStaff { get; set; }
        public Nullable<int> CrtdUserId { get; set; }
        public Nullable<System.DateTime> CrtdTS { get; set; }
        public string SanctionOrderNumber { get; set; }
        public Nullable<System.DateTime> SanctionOrderDate { get; set; }
        public string AgencyRegisteredName { get; set; }
        public Nullable<int> ConsProjectSubType { get; set; }
        public Nullable<int> DurationOfProjectYears { get; set; }
        public Nullable<int> DurationOfProjectMonths { get; set; }
        public Nullable<int> TypeOfProject { get; set; }
        public Nullable<System.DateTime> InputDate { get; set; }
        public Nullable<int> ForgnProjectFundingGovtBody_Qust_1 { get; set; }
        public Nullable<int> ForgnProjectFundingNonGovtBody_Qust_1 { get; set; }
        public string ForgnFundingGovtAgency { get; set; }
        public Nullable<int> ForgnFundingGovtAgencyCountry { get; set; }
        public Nullable<decimal> ForgnForgnFundingGovtAgencyAmount { get; set; }
        public string ForgnFundingNonGovtAgency { get; set; }
        public Nullable<int> ForgnFundingNonGovtAgencyCountry { get; set; }
        public Nullable<decimal> ForgnForgnFundingNonGovtAgencyAmount { get; set; }
        public Nullable<decimal> BaseValue { get; set; }
        public Nullable<decimal> ApplicableTax { get; set; }
        public string Collaborativeprojectcoordinator { get; set; }
        public string CollaborativeprojectAgency { get; set; }
        public string Collaborativeprojectcoordinatoremail { get; set; }
        public Nullable<decimal> Collaborativeprojecttotalcost { get; set; }
        public Nullable<decimal> CollaborativeprojectIITMCost { get; set; }
        public string Agencycontactpersonaddress { get; set; }
        public string ConsForgnCurrencyType { get; set; }
        public string TaxserviceGST { get; set; }
        public Nullable<int> Taxserviceregstatus { get; set; }
        public Nullable<int> SchemeCode { get; set; }
        public Nullable<int> InternalSchemeFundingAgency { get; set; }
        public Nullable<int> ForgnFundGovtBody { get; set; }
        public Nullable<int> ForgnFundNonGovtBody { get; set; }
        public Nullable<int> TaxStatus { get; set; }
        public string JointdevelopmentQuestion { get; set; }
        public string FundingGovtAgencyDept { get; set; }
        public Nullable<decimal> FundingGovtDeptAmount { get; set; }
        public Nullable<decimal> FundingGovtMinistryAmount { get; set; }
        public string FundingGovtUniv { get; set; }
        public Nullable<decimal> FundingGovtUnivAmount { get; set; }
        public string FundingNonGovtAgencyIndustry { get; set; }
        public Nullable<decimal> FundingNonGovtIndstryAmount { get; set; }
        public string FundingNonGovtUniv { get; set; }
        public Nullable<decimal> FundingNonGovtUnivAmount { get; set; }
        public string FundingNonGovtOthers { get; set; }
        public Nullable<decimal> FundingNonGovtOthersAmount { get; set; }
        public Nullable<int> ForgnGovtAgencyDepartmentCountry { get; set; }
        public string ForgnGovtAgencyDepartment { get; set; }
        public Nullable<decimal> ForgnGovtAgencyDepartmentAmount { get; set; }
        public Nullable<int> ForgnGovtUnivCountry { get; set; }
        public string ForgnGovtUniversity { get; set; }
        public Nullable<decimal> ForgnGovtUniversityAmount { get; set; }
        public Nullable<int> ForgnGovtOthersCountry { get; set; }
        public string ForgnGovtOthers { get; set; }
        public Nullable<decimal> ForgnGovtOthersAmount { get; set; }
        public Nullable<int> ForgnNonGovtAgencyDepartmentCountry { get; set; }
        public string ForgnNonGovtAgencyDepartment { get; set; }
        public Nullable<decimal> ForgnNonGovtAgencyDepartmentAmount { get; set; }
        public Nullable<int> ForgnNonGovtAgencyUnivCountry { get; set; }
        public string ForgnNonGovtAgencyUniversity { get; set; }
        public Nullable<decimal> ForgnNonGovtAgencyUnivAmount { get; set; }
        public Nullable<int> ForgnNonGovtOthersCountry { get; set; }
        public string ForgnNonGovtOthers { get; set; }
        public Nullable<decimal> ForgnNonGovtOthersAmount { get; set; }
        public Nullable<decimal> PCF { get; set; }
        public Nullable<decimal> RMF { get; set; }
        public Nullable<bool> IsYearWiseAllocation { get; set; }
        public string ScientistName { get; set; }
        public string ScientistEmail { get; set; }
        public string ScientistMobile { get; set; }
        public string ScientistAddress { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> ConversionRate { get; set; }
        public Nullable<int> SelCurr { get; set; }
        public Nullable<int> CollaborativeProjectType { get; set; }
        public Nullable<bool> IsSubProject { get; set; }
        public Nullable<int> MainProjectId { get; set; }
        public Nullable<int> SequenceNumber { get; set; }
        public Nullable<int> ProjectClassification { get; set; }
    }
}
