//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProcessTransaction
    {
        public int ProcessTransactionId { get; set; }
        public Nullable<int> ProcessGuidelineDetailId { get; set; }
        public Nullable<int> InitiatedUserId { get; set; }
        public Nullable<System.DateTime> InitiatedTS { get; set; }
        public string InitiatedMacID { get; set; }
        public Nullable<bool> Closed_F { get; set; }
        public string ClosingStatus { get; set; }
        public string ActionLink { get; set; }
        public string successMethod { get; set; }
        public string failedMethod { get; set; }
        public Nullable<int> RefId { get; set; }
        public string RefTable { get; set; }
        public string RefFieldName { get; set; }
    }
}
