//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProcessTransactionDetail
    {
        public int ProcessTransactionDetailId { get; set; }
        public Nullable<int> ProcessTransactionId { get; set; }
        public Nullable<int> ProcessGuidelineDetailId { get; set; }
        public Nullable<int> ProcessSeqNumber { get; set; }
        public Nullable<int> Approverid { get; set; }
        public string ActionStatus { get; set; }
        public Nullable<System.DateTime> TransactionTS { get; set; }
        public string TransactionIP { get; set; }
        public string MacID { get; set; }
        public string Comments { get; set; }
        public Nullable<int> RefId { get; set; }
        public string RefTable { get; set; }
        public string RefFieldName { get; set; }
    }
}
