//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPaymentPayee
    {
        public int PaymentPayeeId { get; set; }
        public Nullable<int> PaymentId { get; set; }
        public string PayeeType { get; set; }
        public Nullable<int> PayeeId { get; set; }
        public string PayeeName { get; set; }
        public Nullable<int> BankHeadID { get; set; }
        public string StudentRoll { get; set; }
        public string PayeeBank { get; set; }
        public Nullable<int> PaymentMode { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string TransactionType { get; set; }
        public string Remarks { get; set; }
        public string Branch { get; set; }
        public string IFSC { get; set; }
        public string AccountNumber { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CRTD_TS { get; set; }
        public Nullable<int> CRTD_By { get; set; }
        public Nullable<System.DateTime> UPTD_TS { get; set; }
        public Nullable<int> UPTD_By { get; set; }
        public Nullable<int> PayeeTypeId { get; set; }
    }
}
