//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProposal
    {
        public int ProposalId { get; set; }
        public string ProposalTitle { get; set; }
        public Nullable<int> ProjectType { get; set; }
        public string ProposalNumber { get; set; }
        public Nullable<System.DateTime> InwardDate { get; set; }
        public string Department { get; set; }
        public Nullable<int> PI { get; set; }
        public string PIEmail { get; set; }
        public Nullable<int> SponsoringAgency { get; set; }
        public Nullable<decimal> ProposalValue { get; set; }
        public Nullable<int> DurationOfProject { get; set; }
        public Nullable<int> Scheme { get; set; }
        public string PersonApplied { get; set; }
        public string AttachmentName { get; set; }
        public string AttachmentPath { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> Crtd_Userid { get; set; }
        public Nullable<System.DateTime> Crtd_TS { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> Updt_Userid { get; set; }
        public Nullable<System.DateTime> Updt_TS { get; set; }
        public Nullable<int> FundingGovtBody { get; set; }
        public Nullable<int> ProjectSubType { get; set; }
        public Nullable<int> ProjectCategory { get; set; }
        public Nullable<decimal> BasicValue { get; set; }
        public Nullable<decimal> ApplicableTax { get; set; }
        public Nullable<int> DurationOfProjectMonths { get; set; }
        public Nullable<System.DateTime> Inputdate { get; set; }
        public Nullable<System.DateTime> ProposalApproveddate { get; set; }
        public string PersonAppliedInstitute { get; set; }
        public string PersonAppliedPlace { get; set; }
        public Nullable<int> ProjectSchemeCode { get; set; }
        public string Otherinstcopi_Qust_1 { get; set; }
        public string SanctionNumber { get; set; }
        public Nullable<int> DurationOfProjectYears { get; set; }
        public Nullable<int> ProposalSource { get; set; }
        public Nullable<System.DateTime> TentativeStartDate { get; set; }
        public Nullable<System.DateTime> TentativeCloseDate { get; set; }
        public Nullable<int> FinancialYear { get; set; }
        public Nullable<int> SourceReferenceNumber { get; set; }
        public Nullable<System.DateTime> SourceEmailDate { get; set; }
        public string Status { get; set; }
    }
}
