//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProjectEnhancement
    {
        public int ProjectEnhancementId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public string DocumentReferenceNumber { get; set; }
        public Nullable<bool> IsExtensiononly { get; set; }
        public Nullable<bool> IsEnhancementonly { get; set; }
        public Nullable<bool> IsEnhancementWithExtension { get; set; }
        public Nullable<System.DateTime> PresentDueDate { get; set; }
        public Nullable<System.DateTime> ExtendedDueDate { get; set; }
        public Nullable<decimal> OldSanctionValue { get; set; }
        public Nullable<decimal> EnhancedSanctionValue { get; set; }
        public Nullable<decimal> TotalEnhancedValue { get; set; }
        public Nullable<decimal> TotalAllocatedValue { get; set; }
        public string Status { get; set; }
        public Nullable<int> CrtdUserId { get; set; }
        public Nullable<System.DateTime> CrtsTS { get; set; }
        public Nullable<int> LastUpdtUserId { get; set; }
        public Nullable<System.DateTime> LastUpdtTS { get; set; }
        public string AttachmentName { get; set; }
        public string AttachmentPath { get; set; }
        public Nullable<bool> IsCurrentVersion { get; set; }
        public Nullable<bool> IsExtensionOnlyCurrentversion { get; set; }
    }
}
