//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProjectStaffCategoryMaster
    {
        public int ProjectStaffCategoryId { get; set; }
        public string ProjectStaffCategory { get; set; }
        public Nullable<int> CrtdUserId { get; set; }
        public Nullable<System.DateTime> CrtdTS { get; set; }
        public string Reason { get; set; }
        public Nullable<int> LastUpdatedUserid { get; set; }
        public Nullable<System.DateTime> LastUpdated_TS { get; set; }
        public string Status { get; set; }
    }
}
