//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProjectStatusLog
    {
        public int ProjectStatusLogId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public string FromStatus { get; set; }
        public string ToStatus { get; set; }
        public Nullable<int> UpdtdUserId { get; set; }
        public Nullable<System.DateTime> UpdtdTS { get; set; }
        public Nullable<bool> IsCurrentStatus { get; set; }
        public string Remarks { get; set; }
        public string DocumentName { get; set; }
    }
}
