//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReceipt
    {
        public int ReceiptId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> InvoiceId { get; set; }
        public Nullable<int> BOAId { get; set; }
        public string CommitmentNumber { get; set; }
        public Nullable<decimal> CommitmentAmount { get; set; }
        public string ReceiptNumber { get; set; }
        public Nullable<System.DateTime> ReceiptDate { get; set; }
        public Nullable<decimal> ReceiptAmount { get; set; }
        public Nullable<int> ReceivedFrom { get; set; }
        public Nullable<decimal> ReceivedAmount { get; set; }
        public Nullable<int> BankAccountHeadDr { get; set; }
        public Nullable<decimal> BankAmountDr { get; set; }
        public Nullable<decimal> ReceivablesTotal { get; set; }
        public Nullable<decimal> NetTransactionValue { get; set; }
        public string Description { get; set; }
        public Nullable<int> PaymentMode { get; set; }
        public Nullable<System.DateTime> CrtdTS { get; set; }
        public Nullable<int> CrtdUserId { get; set; }
        public Nullable<int> UpdtUserId { get; set; }
        public Nullable<System.DateTime> UpdtTS { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> ReceiptOverheadValue { get; set; }
        public string RMForCMF { get; set; }
        public Nullable<bool> IsCanceledReceipt { get; set; }
        public Nullable<decimal> SGST { get; set; }
        public Nullable<decimal> CGST { get; set; }
        public Nullable<decimal> IGST { get; set; }
        public Nullable<bool> BackEnd_f { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string TransactionTypeCode { get; set; }
        public Nullable<bool> Adhoc_f { get; set; }
        public Nullable<bool> Project_f { get; set; }
        public Nullable<System.DateTime> ReferenceDate { get; set; }
        public string ReferenceNumber { get; set; }
        public string DocumentActualName { get; set; }
        public string DocumentName { get; set; }
    }
}
