//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReverseTaxDocument
    {
        public int RevereseTaxDocumentId { get; set; }
        public Nullable<int> VendorId { get; set; }
        public string TaxDocument { get; set; }
        public string TaxAttachmentPath { get; set; }
        public string TaxAttachmentName { get; set; }
        public Nullable<int> TaxDocumentType { get; set; }
        public Nullable<bool> IsCurrentVersion { get; set; }
        public Nullable<int> TaxDocumentUploadUserId { get; set; }
        public Nullable<System.DateTime> TaxDocumentUpload_Ts { get; set; }
    }
}
