//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReceiptAgencyShareDetails
    {
        public int ReceiptAgencyId { get; set; }
        public Nullable<int> ReceiptId { get; set; }
        public Nullable<int> ReceiptAgencyHeadId { get; set; }
        public string ReceiptAgencyName { get; set; }
        public Nullable<decimal> ReceiptAgencyAmount { get; set; }
        public Nullable<int> CRTD_By { get; set; }
        public Nullable<System.DateTime> CRTD_TS { get; set; }
        public Nullable<int> UPTD_By { get; set; }
        public Nullable<System.DateTime> UPTD_TS { get; set; }
        public string Status { get; set; }
    }
}
