//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReceiptAllocation
    {
        public int ReceiptAllocationId { get; set; }
        public Nullable<int> ReceiptId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> InvoiceId { get; set; }
        public Nullable<int> BudgetHead { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> CrtdTS { get; set; }
        public Nullable<int> CrtdUserId { get; set; }
        public Nullable<System.DateTime> UpdtTS { get; set; }
        public Nullable<int> UpdtUserId { get; set; }
    }
}
