//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReceiptOverheadBreakup
    {
        public int ReceiptOverheadbreakupId { get; set; }
        public Nullable<int> ReceiptId { get; set; }
        public Nullable<int> ReceiptOverheadTypeId { get; set; }
        public string ReceiptOverheadType { get; set; }
        public Nullable<decimal> ReceiptOverheadAmount { get; set; }
        public Nullable<System.DateTime> CrtdTS { get; set; }
        public Nullable<int> CrtdUserId { get; set; }
        public Nullable<System.DateTime> UpdtTS { get; set; }
        public Nullable<int> UpdtUserId { get; set; }
        public string Status { get; set; }
        public Nullable<bool> IsRMF_f { get; set; }
        public Nullable<bool> ISCMF_f { get; set; }
        public Nullable<bool> IsPosted_f { get; set; }
    }
}
