//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSBIPrepaidCardProjectDetails
    {
        public int SBIECardProjectDetailsId { get; set; }
        public Nullable<int> SBIPrepaidCardDetailsId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> PIId { get; set; }
        public Nullable<decimal> AmountAllocated { get; set; }
        public Nullable<System.DateTime> CrtdTS { get; set; }
        public Nullable<int> CrtdUserId { get; set; }
        public Nullable<System.DateTime> UpdtTS { get; set; }
        public Nullable<int> UpdtUserId { get; set; }
        public string Status { get; set; }
        public Nullable<bool> Is_Recoupmentpending { get; set; }
        public string TransactionTypeCode { get; set; }
        public Nullable<int> CheckListVerifiedBy { get; set; }
        public string SBIPrepaidProjectDetailNumber { get; set; }
    }
}
