//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStaffAppointmentMaster
    {
        public int StaffMasterId { get; set; }
        public Nullable<int> AppointmentTypeId { get; set; }
        public string OrderNumber { get; set; }
        public string FileNumber { get; set; }
        public Nullable<int> StaffID { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public string StaffName { get; set; }
        public string Designation { get; set; }
        public Nullable<int> GenderId { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<System.DateTime> AppointmentFrom { get; set; }
        public Nullable<System.DateTime> AppointmentTo { get; set; }
        public string BankAccount { get; set; }
        public Nullable<int> SalaryType { get; set; }
        public string PAN { get; set; }
        public string MedicalInsurance { get; set; }
        public Nullable<decimal> TA { get; set; }
        public Nullable<decimal> HRA { get; set; }
        public Nullable<decimal> PayableAmount { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    }
}
