//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSRBItemCategory
    {
        public int SRBItemCategotyId { get; set; }
        public string Category { get; set; }
        public Nullable<bool> Asset_f { get; set; }
        public Nullable<System.DateTime> CRTD_TS { get; set; }
        public Nullable<System.DateTime> UPDT_TS { get; set; }
        public Nullable<int> CRTD_UserID { get; set; }
        public Nullable<int> UPDT_UserID { get; set; }
        public string Status { get; set; }
    }
}
