//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSalaryHead
    {
        public int SalaryHeadId { get; set; }
        public string OrderType { get; set; }
        public string EmployeeId { get; set; }
        public string EmpNo { get; set; }
        public Nullable<decimal> Basic { get; set; }
        public Nullable<decimal> MA { get; set; }
        public Nullable<decimal> HRA { get; set; }
        public Nullable<decimal> EPF { get; set; }
        public Nullable<decimal> MedicalInsurance { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    }
}
