//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSRB
    {
        public int SRBId { get; set; }
        public string ItemName { get; set; }
        public string ItemNumber { get; set; }
        public Nullable<System.DateTime> InwardDate { get; set; }
        public string PONumber { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public string ProjectNumber { get; set; }
        public Nullable<int> PIId { get; set; }
        public string Remarks { get; set; }
        public string PODocs { get; set; }
        public Nullable<int> ItemCategoryId { get; set; }
        public Nullable<int> Crt_By { get; set; }
        public Nullable<System.DateTime> Crt_Ts { get; set; }
        public Nullable<int> Updt_By { get; set; }
        public Nullable<System.DateTime> Updt_Ts { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<bool> IsIncludeProjectDetails { get; set; }
        public string SupplierName { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public string InvoiceNumber { get; set; }
        public string SRBNumber { get; set; }
        public Nullable<decimal> NetTotalAmount { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> TaxRate { get; set; }
    }
}
