//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSRBDeactivation
    {
        public int SRBDeactivationId { get; set; }
        public Nullable<int> tblSRBDetailId { get; set; }
        public string ItemName { get; set; }
        public string ItemNumber { get; set; }
        public Nullable<bool> Buyback_f { get; set; }
        public Nullable<decimal> BuybackValue { get; set; }
        public string Comments { get; set; }
        public Nullable<int> SRBId { get; set; }
        public string Attachment { get; set; }
        public Nullable<System.DateTime> CRTD_TS { get; set; }
        public Nullable<System.DateTime> UPDT_TS { get; set; }
        public Nullable<int> CRTD_UserID { get; set; }
        public Nullable<int> UPDT_UserID { get; set; }
        public Nullable<int> BuybackRefId { get; set; }
    }
}
