//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTemporaryAdvance
    {
        public int TemporaryAdvanceId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> PIId { get; set; }
        public string TemporaryAdvanceNumber { get; set; }
        public string TransactionTypeCode { get; set; }
        public string DepartmentorSection { get; set; }
        public Nullable<int> SourceReferenceNumber { get; set; }
        public Nullable<System.DateTime> SourceEmailDate { get; set; }
        public Nullable<int> Source { get; set; }
        public Nullable<System.DateTime> CRTD_TS { get; set; }
        public Nullable<System.DateTime> UPTD_TS { get; set; }
        public Nullable<int> CRTD_By { get; set; }
        public Nullable<int> UPTD_By { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> TotalExpenseValue { get; set; }
        public Nullable<decimal> TemporaryAdvanceAmountReceived { get; set; }
        public string NameofReceiver { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> CommitmentId { get; set; }
        public Nullable<bool> IsPendingSettlement_f { get; set; }
        public Nullable<decimal> ExpenseAmount { get; set; }
        public Nullable<decimal> DeductionAmount { get; set; }
        public Nullable<int> CheckListVerifiedBy { get; set; }
        public Nullable<bool> Pmt_f { get; set; }
    }
}
