//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTapal
    {
        public int TapalId { get; set; }
        public Nullable<int> TapalType { get; set; }
        public string SenderDetail { get; set; }
        public Nullable<bool> ProjectTabal { get; set; }
        public Nullable<int> PIName { get; set; }
        public Nullable<int> ProjectNumber { get; set; }
        public Nullable<bool> IsInward { get; set; }
        public Nullable<System.DateTime> CreatedTS { get; set; }
        public Nullable<int> CreatedUserId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTS { get; set; }
        public Nullable<int> LastUpdatedUserId { get; set; }
        public Nullable<bool> IsClosed { get; set; }
        public string TapalNo { get; set; }
        public string Notes { get; set; }
    }
}
