//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTransactionTypeCode
    {
        public int TransactionTypeCodeId { get; set; }
        public string TransactionType { get; set; }
        public string TransactionTypeCode { get; set; }
        public Nullable<int> EntryTypeId { get; set; }
        public Nullable<int> Functionid { get; set; }
    }
}
