//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTransactionDefinition
    {
        public int TransactionDefinitionId { get; set; }
        public string TransactionTypeCode { get; set; }
        public string SubCode { get; set; }
        public Nullable<int> AccountGroupId { get; set; }
        public Nullable<int> AccountHeadId { get; set; }
        public string TransactionType { get; set; }
        public Nullable<bool> IsJV_f { get; set; }
        public Nullable<decimal> Percentage { get; set; }
    }
}
