//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTemporaryAdvanceSettlementBill
    {
        public int TmpAdvSettlementBillId { get; set; }
        public Nullable<int> TemporaryAdvanceId { get; set; }
        public Nullable<int> TempAdvSettlementId { get; set; }
        public string TmpAdvSettlementBillNumber { get; set; }
        public Nullable<decimal> TotalSettlementBillAmount { get; set; }
        public string VendorName { get; set; }
        public Nullable<decimal> AmountPaidToVendor { get; set; }
        public Nullable<System.DateTime> CRTD_TS { get; set; }
        public Nullable<int> CRTD_By { get; set; }
        public Nullable<System.DateTime> UPDT_TS { get; set; }
        public Nullable<int> UPDT_By { get; set; }
    }
}
