//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTaxMaster
    {
        public int TaxMasterId { get; set; }
        public Nullable<bool> Service_f { get; set; }
        public string ServiceType { get; set; }
        public string TaxCode { get; set; }
        public Nullable<decimal> TaxRate { get; set; }
        public Nullable<bool> IsTaxEligible { get; set; }
    }
}
