//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTapalDocumentDetail
    {
        public int TapalDocumentDetailId { get; set; }
        public Nullable<int> TapalId { get; set; }
        public string FileName { get; set; }
        public string DocumentName { get; set; }
        public Nullable<bool> IsCurrentVersion { get; set; }
    }
}
