//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUpdateLedgerOBLog
    {
        public int UpdateOBLogId { get; set; }
        public Nullable<int> HeadId { get; set; }
        public Nullable<System.DateTime> OBUpdated_Ts { get; set; }
        public Nullable<int> OBUpdatedUserId { get; set; }
        public Nullable<decimal> OBLedgerOldValue { get; set; }
        public Nullable<decimal> OBLedgerCurrentValue { get; set; }
    }
}
