//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<int> Designation { get; set; }
        public Nullable<int> SystemDefaultRole { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> ProfileId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> Gender { get; set; }
        public Nullable<System.DateTime> Dateofbirth { get; set; }
        public Nullable<int> RoleId { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> CRTDDateTS { get; set; }
        public Nullable<System.DateTime> UPDTDateTS { get; set; }
        public Nullable<bool> ApproverF { get; set; }
        public Nullable<int> InstituteId { get; set; }
        public string EMPCode { get; set; }
        public string UserImage { get; set; }
        public Nullable<int> CreatedUserId { get; set; }
        public Nullable<int> LastUpdateUserId { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
    }
}
