//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVoucherDetails
    {
        public int VoucherDetailId { get; set; }
        public int VoucherId { get; set; }
        public Nullable<int> VendorId { get; set; }
        public Nullable<int> SubLedgerId { get; set; }
        public Nullable<int> AccountHeadId { get; set; }
        public Nullable<int> VoucherStatus { get; set; }
        public Nullable<decimal> VoucherAmount { get; set; }
        public Nullable<decimal> PaidAmount { get; set; }
        public Nullable<int> PaymentMode { get; set; }
        public string PayableTo { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    }
}
