//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVoucherHead
    {
        public int VoucherId { get; set; }
        public Nullable<int> ReferenceType { get; set; }
        public string ReferenceNo { get; set; }
        public Nullable<int> RequestId { get; set; }
        public Nullable<System.DateTime> VoucherDate { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<decimal> VoucherAmount { get; set; }
        public Nullable<int> VoucherStatus { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    }
}
