//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVendorTDSDetail
    {
        public int VendorTDSDetailId { get; set; }
        public Nullable<int> VendorId { get; set; }
        public string NatureOfIncome { get; set; }
        public Nullable<decimal> TDSPercentage { get; set; }
        public Nullable<int> Section { get; set; }
    }
}
