//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_BOATransactionDetails
    {
        public Nullable<System.DateTime> PostedDate { get; set; }
        public string ProjectNumber { get; set; }
        public string HeadName { get; set; }
        public string CommitmentNumber { get; set; }
        public string VocherType { get; set; }
        public string TransactionType { get; set; }
        public Nullable<decimal> Amount { get; set; }
    }
}
