//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Postings
    {
        public Nullable<System.DateTime> PostedDate { get; set; }
        public string TransactionTypeCode { get; set; }
        public string TempVoucherNumber { get; set; }
        public string TransType { get; set; }
        public int BOATransactionId { get; set; }
        public int AccountGroupId { get; set; }
        public string Accounts { get; set; }
        public string Groups { get; set; }
        public int AccountHeadId { get; set; }
        public string AccountHead { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string TransactionType { get; set; }
        public Nullable<bool> Creditor_f { get; set; }
        public Nullable<bool> Debtor_f { get; set; }
    }
}
