//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwAccountGroupinHeadwise
    {
        public Nullable<int> AccountGroupId { get; set; }
        public string Accounts { get; set; }
        public string Groups { get; set; }
        public string AccountHead { get; set; }
        public int AccountCategoryId { get; set; }
        public Nullable<decimal> OpeningBal { get; set; }
        public Nullable<int> FinacialYearId { get; set; }
        public int AccountHeadId { get; set; }
        public Nullable<int> HeadOpeningBalanceId { get; set; }
        public string AccountheadStatus { get; set; }
    }
}
