//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwCombineStaffDetails
    {
        public string Category { get; set; }
        public string EmployeeId { get; set; }
        public Nullable<int> ID { get; set; }
        public string Name { get; set; }
        public string DepartmentCode { get; set; }
        public string EmployeeDesignation { get; set; }
        public string DepartmentName { get; set; }
        public string Email { get; set; }
        public string loginid { get; set; }
        public string CONNumber { get; set; }
        public string EmployeePCFId { get; set; }
    }
}
