//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwFacultyStaffDetails
    {
        public string EmployeeId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string FirstName { get; set; }
        public string Designation { get; set; }
        public string DepartmentCode { get; set; }
        public string DepartmentName { get; set; }
        public string Email { get; set; }
        public string ContactNumber { get; set; }
    }
}
