//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWOfficeTransactions
    {
        public string FileNo { get; set; }
        public string AppointmentType { get; set; }
        public string ProjectTitle { get; set; }
        public string PROJECTNO { get; set; }
        public string PTYPE { get; set; }
        public string shon { get; set; }
        public string NAME { get; set; }
        public string departmentcode { get; set; }
        public string DEPARTMENT { get; set; }
        public string SPON { get; set; }
        public string DesignationCode { get; set; }
        public string Designation { get; set; }
        public Nullable<System.DateTime> AppointmentDate { get; set; }
        public Nullable<System.DateTime> ExtensionDate { get; set; }
        public Nullable<System.DateTime> RelieveDate { get; set; }
        public string Paytype { get; set; }
        public Nullable<decimal> BasicPay { get; set; }
        public Nullable<decimal> HRA { get; set; }
        public Nullable<decimal> Medical { get; set; }
        public string CoordinatorCode { get; set; }
        public string phon { get; set; }
        public string CoordinatorName { get; set; }
        public string Community { get; set; }
        public string OldFileno { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string FATHER { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string ADDRESS3 { get; set; }
        public string ADDRESS4 { get; set; }
        public string Gender { get; set; }
        public string BloodGroup { get; set; }
        public string RH { get; set; }
        public string PHONE { get; set; }
        public string R_ADDR1 { get; set; }
        public string R_ADDR2 { get; set; }
        public string R_ADDR3 { get; set; }
        public string R_ADDR4 { get; set; }
        public string COURSE { get; set; }
        public string paybill_id { get; set; }
        public string paybill_no { get; set; }
        public string email_id { get; set; }
        public string Pensioner { get; set; }
        public string Qualification { get; set; }
        public string offerId { get; set; }
        public Nullable<System.DateTime> AppointmentLetterDate { get; set; }
        public string AppointmentLetterNo { get; set; }
        public System.DateTime DateOfInput { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string TransactionType { get; set; }
        public string Filename { get; set; }
        public string username { get; set; }
        public string commitmentNo { get; set; }
        public string HashID { get; set; }
        public string approvedPdf { get; set; }
    }
}
