//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwProposalDetails
    {
        public string Title { get; set; }
        public string Project_Type { get; set; }
        public string PI_Name { get; set; }
        public string Scheme { get; set; }
        public string Agency_Name { get; set; }
        public string Proposal_Number { get; set; }
        public string Proposal_Source { get; set; }
        public Nullable<decimal> Proposal_Value { get; set; }
        public string Department { get; set; }
    }
}
