//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwSRBDetails
    {
        public string ItemName { get; set; }
        public string InwardDate { get; set; }
        public string PONumber { get; set; }
        public string PurchaseDate { get; set; }
        public string ProjectNumber { get; set; }
        public string Remarks { get; set; }
        public int ItemCategory { get; set; }
        public string PIName { get; set; }
    }
}
