//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOAS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwTapalDetails
    {
        public string Sender { get; set; }
        public Nullable<bool> Project_Related { get; set; }
        public Nullable<int> Project_Number { get; set; }
        public string Received_Date { get; set; }
        public string Inward_Date { get; set; }
        public string Comments { get; set; }
        public string Catagory { get; set; }
        public string PI_Name { get; set; }
        public string Outward_Date { get; set; }
        public string To_Department { get; set; }
        public string Recipient { get; set; }
    }
}
